### PR TITLE
Judge make decision - Awaiting Addln Info

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-2405

### Change description ###
Scenario 1:

PreConditionState:  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION

PostConditionState: AWAITING_WRITTEN_REPRESENTATIONS
Scenario 2:

PreConditionState:  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION

PostConditionState: AWAITING_DIRECTIONS_ORDER_DOCS
Scenario 3:

PreConditionState:  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION

PostConditionState: AWAITING_ADDITIONAL_INFORMATION

 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Review by automatemm — APPROVED** [review]

**Review by vasudevganesanhmcts — APPROVED** [review]

**Pull request merged**
